services:
  nginx:
    build:
      context: ./src/services
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - main-network
    volumes:
      - static_volume:/usr/share/nginx/static
      - media_volume:/usr/share/nginx/media

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - main-network
    volumes:
      - redis_data:/data

  backend:
    build: ./src/services/backend
    expose:
      - "8000"
    depends_on:
      - database
      - redis
    env_file:
      - .env
    networks:
      - main-network
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  database:
    image: postgres:15-alpine
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main-network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  main-network:
    driver: bridge