version: '3.8'

services:
  nginx:
    build: 
      context: .
      dockerfile: services/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    volumes:
      - letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - backend
    networks:
      - ft_net
    restart: unless-stopped

  backend:
    build: ./services/backend
    expose:
      - "8000"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - ft_net
    restart: unless-stopped

  database:
    image: postgres:16
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ft_net
    restart: unless-stopped

volumes:
  postgres_data:
  letsencrypt:

networks:
  ft_net:
    driver: bridge
