version: '3.8'

services:
  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - main-network
    volumes:
      - ./services/frontend:/usr/share/nginx/html
      - static_volume:/usr/share/nginx/static
      - media_volume:/usr/share/nginx/media

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - main-network
    volumes:
      - redis_data:/data

  backend:
    build: ./services/backend
    expose:
      - "8000"  # Internal only
    depends_on:
      - database
      - redis
    env_file:
      - .env
    networks:
      - main-network
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  database:
    image: postgres:16
    expose:
      - "5432"  # Internal only
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main-network

volumes:
  redis_data:
  postgres_data:
  static_volume:
  media_volume:

networks:
  main-network:
    driver: bridge