version: '3.8'

services:
  nginx-proxy:
    build: ./services/nginx-proxy
    ports:
      - "80:80"  # Only this needs to be exposed to the internet
    depends_on:
      - backend
      - frontend
    networks:
      - frontend-net
      - backend-net

  frontend:
    build: ./services/frontend
    expose:
      - "8080"  # Internal only
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - frontend-net

  backend:
    build: ./services/backend
    expose:
      - "8000"  # Internal only
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - backend-net

  database:
    image: postgres:16
    expose:
      - "5432"  # Internal only
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

volumes:
  postgres_data:

networks:
  frontend-net:  # For nginx and frontend
  backend-net:   # For nginx, backend and database